# Generated by Django 3.2.9 on 2021-11-06 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, related_name='responders', to='api.Question'),
        ),
        migrations.AlterField(
            model_name='responder',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999-999-9999'.", regex='^\\+?1?\\d{5}-\\d{3}-\\d{4}$')]),
        ),
    ]
