# Generated by Django 3.2.9 on 2021-11-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211106_0141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responder',
            unique_together={('name', 'phone_number')},
        ),
    ]
