# Generated by Django 3.2.9 on 2021-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_responder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='answers', to='api.Responder'),
        ),
    ]
